# Generated by Django 6.0 on 2026-03-15 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=14)),
                ('pincode', models.CharField(max_length=10)),
                ('flat', models.CharField(max_length=250, verbose_name='Flat, House no., Building, Company, Apartment')),
                ('area', models.CharField(max_length=250, verbose_name='Area, Street, Sector, Village')),
                ('landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=250, verbose_name='Town/City')),
                ('state', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_mobile_number', models.CharField(blank=True, max_length=14, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
