# Generated by Django 6.0 on 2026-09-30 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_productvariant_price'),
        ('home', '0008_remove_orders_variant_orders_address_orders_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=14)),
                ('pincode', models.CharField(max_length=10)),
                ('flat', models.CharField(max_length=250, verbose_name='Flat, House no., Building, Company, Apartment')),
                ('area', models.CharField(max_length=250, verbose_name='Area, Street, Sector, Village')),
                ('landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=250, verbose_name='Town/City')),
                ('state', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending')),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Netbanking', 'Netbanking'), ('Card', 'Card'), ('Cash on Delivery', 'Cash on Delivery')], null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Netbanking', 'Netbanking'), ('Card', 'Card'), ('Cash on Delivery', 'Cash on Delivery')], null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=300, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=300, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
