# Generated by Django 6.0 on 2026-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_order_orderitem_payment_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
            preserve_default=False,
        ),
    ]
